version: '3.1'
services:
  mongo-server:
      image: mongo:latest
      container_name: mongo-server
      restart: always
      # command: mongod --noauth --smallfiles
      volumes:
      - ./data/:/data/db
      ports:
      - 27017:27017
      # to access CLI `docker exec -it mongo-server mongo`
  idea-launchpad:
    image:  idea-launchpad:latest
    # container_name: docker-app-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8080:4000"
    environment:
      PORT: "4000"